### ISSUE TITLE
Error when trying to use setup.py

### ISSUE THREAD

**Issue by Karmiven** [tonymmm1/vmangos-docker#15]
```
ubuntu@ubuntu:~/vmangos-docker$ ./setup.py -m 0 -t 2 -u 1000:1000 -c 5875 -a 1
Beginning VMaNGOS setup
fatal: unsafe repository ('/home/ubuntu/vmangos-docker' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/ubuntu/vmangos-docker
Traceback (most recent call last):
  File "./setup.py", line 344, in <module>
    git_submodules()
  File "./setup.py", line 186, in git_submodules
    subprocess.run(['git','submodule','update','--init','--remote','--recursive'],check=True)   #git submodule update --init --remote --recursive -j $(nprocs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--remote', '--recursive']' returned non-zero exit status 128.
```
```
ubuntu@ubuntu:~/vmangos-docker$ pip3 -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

maybe it wont to work with 3.8 python?

```
ubuntu@ubuntu:~/vmangos-docker$ docker -v
Docker version 20.10.14, build a224086
ubuntu@ubuntu:~/vmangos-docker$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

**Comment by tonymmm1** [comment]
It looks to me like the directory is not owned by the user input and thus failing.
